### ISSUE TITLE
[Hermes] New application for contracts

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#13]
Create codbex-contract with entities

Contract:
- Number
- StartDate
- EndDate
- Company
- Contract type
- Url
- Comment

**Comment by TIVMOF** [comment]
[codbex-contracts repo](https://github.com/codbex/codbex-contracts)

**Comment by nedelcho-delchev-tues** [comment]
fixed with the initial commits from https://github.com/codbex/codbex-contracts repo
