### ISSUE TITLE
[Hermes] Regenerate and fix codbex-opportunities

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#16]
The project [codbex-hermes](https://github.com/codbex/codbex-opportunities) needs to be regenerated with the newest version of Dirigible and to check if everything works as expected.

If something is needed it will be discussed.

**Comment by TIVMOF** [comment]
[Link to PR](https://github.com/codbex/codbex-opportunities/pull/11)

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-opportunities/pull/11
