### ISSUE TITLE
[Athena] Navigations order

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#165]
Expected order of navigation tabs is needed according to app's logic. The aim of this issue is to have a list of these navigation tabs ordered accordingly. 

For example the navigation tabs here are not still ordered and don't follow certain logic:
![Image](https://github.com/user-attachments/assets/203de38a-6103-4c9d-9602-312df4f2fb97)

**Comment by Mrgoblings** [comment]
Purchasing:
- Purchase Invoice
- Supplier Payment

Sales:
- Sales Invoice
- Customer Payment
- Debit Note
- Credit Note

Employees:
- Employees
- Contacts
- Organizations
- Job Assessments

Partners:
- Manufacturers
- Suppliers
- Customers

Configuration:
- Companies
- Methods
- Currencies
- Dimensions
- Countries
- Cities
- Units of Measurements

**Comment by bob4o-afk** [comment]
### Project
- Project  
  - Projects  
  - Deliverables  

---

### People
- Employees  
  - Organisations  
  - Employees  

---

### Settings
- Configurations  
  - AgileMethodology  
  - ApprovalStatus  
  - CostCategory  
  - ExpenseCategory  
  - IterationLength  
  - MemberRole  
  - ResourceType  
  - StakeHolderType  
  - StatusType
