### ISSUE TITLE
[Hera] Navigations order

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#166]
Expected order of navigation tabs is needed according to app's logic. The aim of this issue is to have a list of these navigation tabs ordered accordingly. 

For example the navigation tabs here are not still ordered and don't follow certain logic:
![Image](https://github.com/user-attachments/assets/3e433762-6b1a-43ba-baa0-56b348ad0563)

**Comment by NicoleNG18** [comment]
### Company:   

- Companies
- Organizations
- Teams

### Employees: 

- Employees
- Documents
- Jobs
- Leave Requests

### Salaries: 

- Salaries
- Payrolls
- Employee payments
