### ISSUE TITLE
[Jason] Navigations order

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#167]
Expected order of navigation tabs is needed according to app's logic. The aim of this issue is to have a list of these navigation tabs ordered accordingly. 

For example the navigation tabs here are not still ordered and don't follow certain logic:
![Image](https://github.com/user-attachments/assets/144a7c46-8a61-46cd-97ab-cf6e8638247e)

**Comment by bob4o-afk** [comment]
### Project
- Project  
  - Projects  
  - Deliverables  

---

### People
- Employees  
  - Organisations  
  - Employees  

---

### Settings
- Configurations  
  - AgileMethodology  
  - ApprovalStatus  
  - CostCategory  
  - ExpenseCategory  
  - IterationLength  
  - MemberRole  
  - ResourceType  
  - StakeHolderType  
  - StatusType
