### ISSUE TITLE
[Plutus] Navigations order

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#168]
Expected order of navigation tabs is needed according to app's logic. The aim of this issue is to have a list of these navigation tabs ordered accordingly. 

For example the navigation tabs here are not still ordered and don't follow certain logic:
![Image](https://github.com/user-attachments/assets/6120b3e7-037d-4714-b5fc-9274629b698c)

**Comment by alt-plus-f4** [comment]
Add Navigations in this order:
1. assets
2. acquisitions (maybe in inventory)
3. asset deprecations
4. asset valuation
6. asset maintenance
7. asset disposal

Separate group:
![Image](https://github.com/user-attachments/assets/c12551d3-a90b-4490-b1ee-f0e4c58018a7)


Separate configuration entities:
![Image](https://github.com/user-attachments/assets/46580b81-0692-442c-857f-2c41a5f161fa)

**Comment by alt-plus-f4** [comment]
Assets:

- assets
- acquisitions
- asset deprecations
- asset valuation
- asset maintenance
- asset disposal

Purchasing:

- Purchase Invoice
- Supplier Payment

Sales:

- Sales Invoice
- Customer Payment
- Debit Note
- Credit Note

Employees:

-  Employees
-  Contacts
-  Organizations
-  Job Assessments

Partners:

-  Manufacturers
-  Suppliers
-  Customers

Inventory:

- Products
- Waste

Configuration:   
- Companies
- Methods
    - ValuationMethod
    - MaintenanceStatus
    - DisposalMethod (from asset)
- Currencies
- Dimensions
-  Countries
-  Cities
-  Units of Measurements
