### ISSUE TITLE
[Hermes] Navigations order

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#169]
Expected order of navigation tabs is needed according to app's logic. The aim of this issue is to have a list of these navigation tabs ordered accordingly. 

For example the navigation tabs here are not still ordered and don't follow certain logic:
![Image](https://github.com/user-attachments/assets/f4e45e97-37a6-4913-bd56-473966b2ef73)

**Comment by TIVMOF** [comment]
Navigation tab order for Hermes:
1. Dashboard
2. Opportunity
3. Sales
4. Purchasing
5. Products
6. Employees
7. Partners
8. Finance
9. Configurations
