### ISSUE TITLE
[Hermes] Initial dashboard

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#17]
Implement Athena's dashboard similiar to how codbex-hestia is currently.

For now only a skeleton will be sufficient with index.html and angular setup, all entities from codbex-opportunities, sales orders and contracts.

**Comment by TIVMOF** [comment]
[Link to PR](https://github.com/codbex/codbex-hermes/pull/52)

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-hermes/pull/52
