### ISSUE TITLE
[Hestia] Product catalogue for current stock availability 

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#18]
Add Catalogue entity in `codbex-products` that will keep current stock availability for each product in each `Store` 

Properties:
- Id
- Product
- Store
- Quantity

**Comment by MinaDoncheva** [comment]
https://github.com/codbex/codbex-products/pull/4
https://github.com/codbex/codbex-hestia/pull/26

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-products/pull/4 and https://github.com/codbex/codbex-hestia/pull/26
