### ISSUE TITLE
[Hestia] Product catalogue events for adjustment

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#19]
To adjust the quantity for each product in the product catalogue we need events for the following entities.

- GoodsIssue/GoodsIssueItems
- GoodsReceipt/GoodsReceiptItems
- StockAdjustment/StockAdjustmentItems

The event should handle each item `on-create` and adjust the `Quantity` property in the `Catalogue` entity.

**Comment by MinaDoncheva** [comment]
https://github.com/codbex/codbex-inventory/pull/2

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-inventory/pull/2
