### ISSUE TITLE
[Modules] Refactor widgets, navigations & reports

### ISSUE THREAD

**Issue by Mrgoblings** [codbex/codbex-olympus#190]
1. Navigations & Widgets refactor file structure & file names
- ***Navigations***:
![Image](https://github.com/user-attachments/assets/115a9d10-e885-450b-b37a-7f1b12663f34)

- ***Widgets***:
![Image](https://github.com/user-attachments/assets/e360b838-9f1c-4325-afd0-fea09aba9d1d)

---

2. Navigations ***service.js*** 
- Property `orderNumber` to be renamed to `order` and set the corrected value from the [Navigation List](https://docs.google.com/document/u/1/d/1RxV357RTSXk7JWwyQrynHgQyv-UEgjRRilR06t4ZTsg/edit?usp=sharing)
- Remove property `view`
- Remove property `lazyload`

### Before:
```js
const navigationData = {
    id: 'credit-notes-navigation',
    label: "Credit Notes",
    view: "credit-notes",
    group: "sales",
    orderNumber: 1000,
    lazyLoad: true,
    link: "/services/web/codbex-invoices/gen/codbex-invoices/ui/CreditNote/index.html?embedded"
};
```

### After:
```js
const navigationData = {
    id: 'credit-notes-navigation',
    label: "Credit Notes",
    group: "sales",
    order: 1000,
    link: "/services/web/codbex-invoices/gen/codbex-invoices/ui/CreditNote/index.html?embedded"
};
```

---

3. Widget ***service.js*** file needs 
- Add property `redirectViewId` **only if needed**. <h6> When a widget is clicked it will redirect the current view to the one given. A valid redirectViewId is any "id" property from a navigation service.js file</h6>
- Remove property `lazyload` 

### Before:
```js
const widgetData = {
    id: 'gross-profit-widget',
    label: 'Gross Profit Widget',
    link: '/services/web/codbex-invoices/widgets/subviews/gross-profit.html',
    lazyLoad: true,
    size: "medium"
};
```

### After:
```js
const widgetData = {
    id: 'gross-profit-widget',
    label: 'Gross Profit Widget',
    link: '/services/web/codbex-invoices/widgets/subviews/gross-profit.html',
    redirectViewId: 'credit-notes-navigation', // OPTIONAL - if the property is missing the widget won't redirect 
    size: "small"
};
```
 
4. Widgets Refactor
- ***index.html*** swap *<style>* tag with this - 
```style.css
<style>
        .tile-auto-layout {
            min-height: auto;
            height: auto;
            width: auto;
            max-width: 99%;
            margin: 1px;
        }

        .overflow-h {
            overflow: hidden;
        }

        .fd-numeric-content__kpi {
            font-size: 1.5rem;
            word-wrap: break-word;
            text-overflow: ellipsis;
            font-weight: 500;
            white-space: nowrap;
            overflow: hidden;
        }
    </style>
```
- ***index.html*** Remove the Redundant Wrapper div:
    - Delete the outer `<div class="fd-col fd-col--x fd-col-md--x fd-col-lg--x fd-col-xl--x">`. The tile widget will now be directly placed in the <body> tag.

- ***index.html*** Add class="overflow-h" to <body>
    - The opening tag oh the body should look like this:
```
<body class="overflow-h">
``` 

- ***index.html*** - Remove **unnecessary** nesting of child elements if present
 
- ***controller.js*** remove `$scope.openPerspective` if present
![Image](https://github.com/user-attachments/assets/f683e2c2-81f3-4e60-998f-9b09e9447d52)

---

5. Reports need regenerating

---

6. Add `codbex-navigation-groups` as a dependency to all modules in *project.json*:
```json
{
    "guid": "codbex-navigation-groups",
    "type": "git",
    "url": "https://github.com/codbex/codbex-navigation-groups",
    "branch": "main"
}
```

---

7. Add github action for building, releasing and deploying to modules and applications that don't have.

**Comment by TIVMOF** [comment]
working on:
codbex-payrolls
codbex-jobs

**Comment by Mrgoblings** [comment]
codbex-accounts

**Comment by TIVMOF** [comment]
working on:
codbex-cities
codbex-companies
codbex-contracts
codbex-countries

**Comment by TIVMOF** [comment]
working on: 
codbex-currencies
codbex-employees
codbex-organizations

**Comment by Mrgoblings** [comment]
Working on:
- codbex-industries
- codbex-inventory
- codbex-methods
- codbex-orders

**Comment by TIVMOF** [comment]
working on:
- codbex-payments
- codbex-partners
- codbex-uoms

**Comment by TIVMOF** [comment]
working on:
- codbex-industries
- codbex-inventory
- codbex-products
- codbex-methods
- codbex-orders

**Comment by TIVMOF** [comment]
working on:
- codbex-opportunities
- codbex-projects
- codbex-salaries
- codbex-vacations
- codbex-assets
