### ISSUE TITLE
[Reports] New input `order` when generating a report

### ISSUE THREAD

**Issue by Mrgoblings** [codbex/codbex-olympus#201]
Make a PR to the Eclipse Dirigible that adds a field Order in the second section of the report generating wizard. This property will be placed in the navigation service of the report. It will serve as an index by witch the dashboard should order the reports' navigations in the Report group.

**Comment by TIVMOF** [comment]
This issue references eclipse/dirigible/issues/4501

**Comment by ThuF** [comment]
PR merged in the Eclipse Dirigible repository, the feature would be available with the next release. @Mrgoblings, @TIVMOF I'm closing this issue, as there is nothing else to be done in it.
