### ISSUE TITLE
[Modules] Release after refactoring

### ISSUE THREAD

**Issue by TIVMOF** [codbex/codbex-olympus#206]
Make a new release for each module to include the new refactoring.

Go to the Actions tab in the GitHub Repository. From the vertical menu on the right choose release. Click the Run workflow button. In the Release Version field write the updated version (if previous one was 0.3.0, then the new one will be 0.4.0). Click the green Run workflow button.

Start from the modules that don't depend on other packages. After that you should update the version of the respective package in every module's package.json. That way you remove the risk of packages being build with older versions of dependencies. Make sure all package versions correspond with the actual release.

Modules that don't depend on packages:
- [codbex-countries](https://github.com/codbex/codbex-countries)
- [codbex-currencies](https://github.com/codbex/codbex-currencies)
- [codbex-accounts](https://github.com/codbex/codbex-accounts)
- [codbex-uoms](https://github.com/codbex/codbex-uoms)
- [codbex-industries](https://github.com/codbex/codbex-industries)
- [codbex-methode](https://github.com/codbex/codbex-methods)
- [codbex-vacations](https://github.com/codbex/codbex-vacations)
- [codbex-templates](https://github.com/codbex/codbex-templates)
- [codbex-navigation-groups](https://github.com/codbex/codbex-navigation-groups)
- [codbex-number-generator](https://github.com/codbex/codbex-number-generator)
- [codbex-branding](https://github.com/codbex/codbex-branding)
- all data modules
   - [codbex-methods-data](https://github.com/codbex/codbex-methods-data)
   - [codbex-cities-data](https://github.com/codbex/codbex-cities-data)
   - [codbex-countries-data](https://github.com/codbex/codbex-countries-data)
   - [codbex-uoms-data](https://github.com/codbex/codbex-uoms-data)
   - [codbex-accounts-data](https://github.com/codbex/codbex-accounts-data)
   - [codbex-number-generator-data](https://github.com/codbex/codbex-number-generator-data)
   - [codbex-currencies-data](https://github.com/codbex/codbex-currencies-data)
   - [codbex-employees-data](https://github.com/codbex/codbex-employees-data)
   - [codbex-payments-data](https://github.com/codbex/codbex-payments-data)
   - [codbex-invoices-data](https://github.com/codbex/codbex-invoices-data)
- all data-sample projects:
   - [codbex-plutus-data-sample](https://github.com/codbex/codbex-plutus-data-sample/)
   - [codbex-hera-data-sample](https://github.com/codbex/codbex-hera-data-sample/)
   - [codbex-jason-data-sample](https://github.com/codbex/codbex-jason-data-sample/)
   - [codbex-hestia-data-sample](https://github.com/codbex/codbex-hestia-data-sample/)
   - [codbex-athena-data-sample](https://github.com/codbex/codbex-athena-data-sample/)
   - [codbex-hermes-data-sample](https://github.com/codbex/codbex-hermes-data-sample/)
- all extension projects:
   - [codbex-order-inventory-ext](https://github.com/codbex/codbex-order-inventory-ext)
   - [codbex-order-invoice-ext](https://github.com/codbex/codbex-order-invoice-ext)
   - [codbex-invoice-inventory-ext](https://github.com/codbex/codbex-invoice-inventory-ext)
   - [codbex-order-payment-ext](https://github.com/codbex/codbex-order-payment-ext)
   - [codbex-payment-order-ext](https://github.com/codbex/codbex-payment-order-ext)
   - [codbex-payment-invoice-ext](https://github.com/codbex/codbex-payment-invoice-ext)
   - [codbex-lead-customer-ext](https://github.com/codbex/codbex-lead-customer-ext)
   - [codbex-disposal-orders-ext](https://github.com/codbex/codbex-disposal-orders-ext)
   - [codbex-invoices-ext](https://github.com/codbex/codbex-invoices-ext)
   - [codbex-perseus-ext](https://github.com/codbex/codbex-perseus-ext)
- all print projects:
   - [codbex-hestia-print](https://github.com/codbex/codbex-hestia-print)

Next are modules depending on packages. They are arranged in waves that should be released in that order. They can safely be released only after incrementing the versions in their package.json.

First wave:
- [codbex-cities](https://github.com/codbex/codbex-cities)

Next wave:
- [codbex-partners](https://github.com/codbex/codbex-partners)
- [codbex-jobs](https://github.com/codbex/codbex-jobs)

Next wave:
- [codbex-contracts](https://github.com/codbex/codbex-contracts)
- [codbex-products](https://github.com/codbex/codbex-products)
- [codbex-organizations](https://github.com/codbex/codbex-organizations)

Next wave:
- [codbex-employees](https://github.com/codbex/codbex-employees)
- [codbex-rfqs](https://github.com/codbex/codbex-rfqs)
- [codbex-bids](https://github.com/codbex/codbex-bids)
- [codbex-inventory](https://github.com/codbex/codbex-inventory)

Next wave:
- [codbex-companies](https://github.com/codbex/codbex-companies)
- [codbex-projects](https://github.com/codbex/codbex-projects)
- [codbex-salaries](https://github.com/codbex/codbex-salaries)
- [codbex-payments](https://github.com/codbex/codbex-payments)

Next wave:
- [codbex-payrolls](https://github.com/codbex/codbex-payrolls)
- [codbex-orders](https://github.com/codbex/codbex-orders)
- [codbex-invoices](https://github.com/codbex/codbex-invoices)

Next wave:
- [codbex-opportunities](https://github.com/codbex/codbex-opportunities)
- [codbex-assets](https://github.com/codbex/codbex-assets)
- [codbex-appointments](https://github.com/codbex/codbex-appointments)

Finally there are the applications projects:
- [codbex-hestia](https://github.com/codbex/codbex-hestia)
- [codbex-hermes](https://github.com/codbex/codbex-hermes)
- [codbex-athena](https://github.com/codbex/codbex-athena)
- [codbex-hera](https://github.com/codbex/codbex-hera)
- [codbex-jason](https://github.com/codbex/codbex-jason)
- [codbex-plutus](https://github.com/codbex/codbex-plutus)

**Comment by TIVMOF** [comment]
This issue references #190

**Comment by ThuF** [comment]
@TIVMOF could you please add links to the respective repositories? So it would be easier to navigate from here?

**Comment by TIVMOF** [comment]
> [@TIVMOF](https://github.com/TIVMOF) could you please add links to the respective repositories? So it would be easier to navigate from here?

Done
