### ISSUE TITLE
[Hermes] Test data for Hermes

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#21]
Generate test data for Hermes similar to https://github.com/codbex/codbex-hestia-data-sample

We need test data for codbex-opportunities enitites, etc.

**Comment by TIVMOF** [comment]
[Link to Hermes sample data](https://github.com/codbex/codbex-hermes-data-sample/pull/1)
[Link to additional fixes in codbex-opportunities](https://github.com/codbex/codbex-opportunities/pull/13)

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-hermes-data-sample/pull/1
