### ISSUE TITLE
[Research][Hermes] Research dashboard widgets/reports

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#27]
We need to research how the dashboard should look like with all widgets and reports.

**Comment by TIVMOF** [comment]
Documentation showing the research:
- [Widgets](https://docs.google.com/document/d/1MJNzZGn1aHc21w-KH4Qir7QfZ2O9Wzakk2BNU7_4s3c/edit?usp=sharing)
- [Reports at the end of the file](https://docs.google.com/document/d/1InCxw5oBo9G-urlaFs_7WsYA8IVweS8t7J2q9hmTWHc/edit?usp=sharing)
