### ISSUE TITLE
[Olympus] Regenerate modules according to new template

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#30]
Gen folders must be deleted and regenerated from the edm. Paths and extensions must be fixed according to the new structure

**Comment by MinaDoncheva** [comment]
fixed with https://github.com/codbex/codbex-hestia/pull/33, https://github.com/codbex/codbex-products/pull/7, https://github.com/codbex/codbex-order-invoice-ext/pull/1, https://github.com/codbex/codbex-methods/pull/2, https://github.com/codbex/codbex-inventory/pull/6, https://github.com/codbex/codbex-order-inventory-ext/pull/4, https://github.com/codbex/codbex-companies/pull/3, https://github.com/codbex/codbex-employees/pull/14, https://github.com/codbex/codbex-payments/pull/14, https://github.com/codbex/codbex-invoices/pull/16, https://github.com/codbex/codbex-partners/pull/15, https://github.com/codbex/codbex-countries/pull/13, https://github.com/codbex/codbex-currencies/pull/14, https://github.com/codbex/codbex-uoms/pull/15, https://github.com/codbex/codbex-cities/pull/1, https://github.com/codbex/codbex-orders/pull/17

**Comment by Mrgoblings** [comment]
fixed with codbex/codbex-accounts#3

**Comment by TIVMOF** [comment]
fixed with [codbex/codbex-opportunities#14](https://github.com/codbex/codbex-opportunities/pull/14), [codbex/codbex-contracts#2](https://github.com/codbex/codbex-contracts/pull/2), [codbex/codbex-industries#14](https://github.com/codbex/codbex-industries/pull/14)
