### ISSUE TITLE
[Hestia] Create Delivery Note entity

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#36]
We need Delivery Note which will be used for information between the client and the employees about the items from an order that can be picked from the inventory. It will include only information about the quantity of the product.

**Comment by TIVMOF** [comment]
fixed with https://github.com/codbex/codbex-inventory/pull/17, https://github.com/codbex/codbex-order-inventory-ext/pull/9 and https://github.com/codbex/codbex-hestia-dashboard/pull/37

**Comment by MinaDoncheva** [comment]
It must contain the information about the quantity of the products that can be picked. Generate Delivery Note must offer list of "Issued" items and the user would choose which to include.
