### ISSUE TITLE
[Hestia] Create codbex-orders-payments-ext

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#39]
Add button for adding payments based on SalesOrder. It must include the amount if it is partial and the payment method.

**Comment by NicoleNG18** [comment]
fixed with 
https://github.com/codbex/codbex-order-payment-ext/pull/1
https://github.com/codbex/codbex-orders/pull/29
https://github.com/codbex/codbex-payments/pull/21 
https://github.com/codbex/codbex-hestia-dashboard/pull/40
