### ISSUE TITLE
[Hestia] Create Credit/Debit note entities

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#40]
Credit/Debit Note is a document which changes the net amount of an invoice. We can create and receive those documents. We want to be able to create such document using custom action from SalesInvoice and fill only the new amount. We can only receive those documents so it is necessary to store them in the Purchase perspective. 

**What are Credit and Debit Notes**
Дебитното и кредитното известие са данъчни документи, с които се документира изменението на данъчната основа или развалянето на доставката. В случай на такова изменение доставчикът е длъжен да издаде съответното известие към фактурата:
- дебитно известие – когато данъчната основа се е изменила в посока увеличение
- кредитно известие – когато данъчната основа се е изменила в посока намаление или при разваляне на доставката
Дебитното и кредитното известие съдържат същите реквизити като фактурата. Освен тях, в известията задължително се посочват и номер и дата на фактурата, към която се издава съотетното известие, и основание за издването му.

**Comment by Mrgoblings** [comment]
fixed with

- https://github.com/codbex/codbex-invoices/pull/30
- https://github.com/codbex/codbex-hestia-dashboard/pull/42
