### ISSUE TITLE
[Hestia] Add "Waste" template in Inventory

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#44]
Create entity Waste as part of codbex-inventory. It should contain Number, Date, Supplier, Product, Quantity, Store and Reason properties and remove units from the catalogue quantity using an event.

**Comment by bob4o-afk** [comment]
fixed with:
- https://github.com/codbex/codbex-hestia-dashboard/pull/43
- https://github.com/codbex/codbex-inventory/pull/26
