### ISSUE TITLE
[Olympus] Create module codbex-hestia-print

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#45]
Put all print templates in a single module.
Templates:
https://github.com/codbex/codbex-invoices/tree/main/codbex-invoices/print
https://github.com/codbex/codbex-orders/tree/main/codbex-orders/print
and to check if there are other similar templates through the modules

**Comment by MinaDoncheva** [comment]
fixed with:
- https://github.com/codbex/codbex-hestia-print
- https://github.com/codbex/codbex-invoices/pull/29
- https://github.com/codbex/codbex-inventory/pull/21
- https://github.com/codbex/codbex-orders/pull/24
- https://github.com/codbex/codbex-hestia-dashboard/pull/38

**Comment by ThuF** [comment]
@MinaDoncheva all PRs were merged, should we consider this issue done?
