### ISSUE TITLE
[Hestia] Add Delivery Note number signature to codbex-number-generator

### ISSUE THREAD

**Issue by MinaDoncheva** [codbex/codbex-olympus#47]
Create signature "DN" for Delivery Note Number in codbex-number-generator-data

**Comment by TIVMOF** [comment]
DN signature is already in use. DE was used instead.

**Comment by TIVMOF** [comment]
fixed with https://github.com/codbex/codbex-number-generator/pull/4 and https://github.com/codbex/codbex-number-generator/pull/5,
