### ISSUE TITLE
[Hestia] Load widgets from extension point

### ISSUE THREAD

**Issue by Mrgoblings** [codbex/codbex-olympus#70]

**Comment by Mrgoblings** [comment]
solved with 
- https://github.com/codbex/codbex-invoices-widgets
- https://github.com/codbex/codbex-products-widgets
- https://github.com/codbex/codbex-orders-widgets

**Comment by MinaDoncheva** [comment]
fixed with:

- https://github.com/codbex/codbex-invoices/pull/35
- https://github.com/codbex/codbex-products/pull/21
- https://github.com/codbex/codbex-orders/pull/33
