### ISSUE TITLE
[Hermes] Remove current EDM and add new entities

### ISSUE THREAD

**Issue by nedelcho-delchev-tues** [codbex/codbex-olympus#9]
We need to scrap the current `Hermes` implementation and add the following entities:

- leads(codbex-opportunities)
- opportunities(codbex-opportunities)
- quotations(codbex-opportunities)
- sales orders/ work orders(codbex-orders)
- contracts(codbex-contracts)

**Comment by TIVMOF** [comment]
[Link to PR](https://github.com/codbex/codbex-hermes/pull/51)

**Comment by nedelcho-delchev-tues** [comment]
fixed with https://github.com/codbex/codbex-hermes/pull/51
