### ISSUE TITLE
[Modules] Move data projects into main project

### ISSUE THREAD

**Issue by Mrgoblings** [codbex/codbex-olympus#97]
We need to transfer the data projects into the main projects.

Example: In the repository codbex-orders there are two projects: codbex-orders and codbex-orders-data. The data project should be moved inside the main project as a folder without the project files (project.json and package.json)

The paths to the csv files in the csvim file should be updated. 
After that in the package.json of the main and now only project in the repo if the data package is listed in the dependencies it should be removed.
Finally in the release.yaml any mentions of the data project/package should be removed as well.

List of modules:
https://github.com/codbex/codbex-orders
https://github.com/codbex/codbex-accounts
https://github.com/codbex/codbex-industries
https://github.com/codbex/codbex-countries
https://github.com/codbex/codbex-currencies
https://github.com/codbex/codbex-invoices
https://github.com/codbex/codbex-inventory
https://github.com/codbex/codbex-appointments
https://github.com/codbex/codbex-products
https://github.com/codbex/codbex-bids
https://github.com/codbex/codbex-contracts
https://github.com/codbex/codbex-methods
https://github.com/codbex/codbex-payments
https://github.com/codbex/codbex-rfqs
https://github.com/codbex/codbex-employees
https://github.com/codbex/codbex-opportunities

**Comment by TIVMOF** [comment]
Started working on codbex-orders.

**Comment by NicoleNG18** [comment]
Started working on codbex-accounts, codbex-industries, codbex-countries, codbex-currencies, codbex-invoices,codbex-inventory

**Comment by TIVMOF** [comment]
Started working codbex-appointments, codbex-products, codbex-bids

**Comment by NicoleNG18** [comment]
Started working codbex-contracts, codbex-methods, codbex-payments

**Comment by TIVMOF** [comment]
Started working on codbex-rfqs, codbex-employees, codbex-opportunities
